-- Audio media library. Files live in S3/MinIO; this table is the index.
-- IDs are UUIDs generated by the relay (TEXT for consistency with the rest of the schema).
-- size_bytes and duration_seconds are client-reported on confirm — nullable, for display only.

CREATE TABLE IF NOT EXISTS audio_media (
    id               TEXT        NOT NULL PRIMARY KEY,
    object_key       TEXT        NOT NULL UNIQUE,  -- S3 key, server-generated (never trust client)
    filename         TEXT        NOT NULL,
    content_type     TEXT        NOT NULL,
    size_bytes       BIGINT,
    duration_seconds REAL,
    uploaded_by      TEXT        NOT NULL,          -- admin UUID (AdminClaims.sub)
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
